<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260617180626 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase 2: SystemEinstellung, Tisch-Lifecycle-Felder (autoStart, naechsterSpielstartAm, menschenloseSeitAm, regelEinstellungen), TischSpieler-Felder (moechteNachSpielVerlassen, disconnectSeitAm)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE system_einstellungen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, schluessel VARCHAR(100) NOT NULL, wert VARCHAR(500) NOT NULL, beschreibung VARCHAR(255) DEFAULT NULL, aktualisiert_am TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DB9A8147AD8C79B6 ON system_einstellungen (schluessel)');
        $this->addSql('COMMENT ON COLUMN spiele.aktueller_zug_begann_am IS \'\'');
        $this->addSql('ALTER TABLE tisch_spieler ADD moechte_nach_spiel_verlassen BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE tisch_spieler ADD disconnect_seit_am TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE tische ADD auto_start BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE tische ADD naechster_spielstart_am TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE tische ADD menschenlose_seit_am TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $defaultRegelwerk = json_encode([
            'soli_erlaubt'       => ['SOLO_BUBEN', 'SOLO_DAMEN', 'SOLO_FLEISCHLOS', 'SOLO_KARO', 'SOLO_HERZ', 'SOLO_PIK', 'SOLO_KREUZ'],
            'solist_kommt_raus'  => true,
            'schweinchen'        => false,
            'superschweinchen'   => false,
            'ohne_neuner'        => false,
            'armut'              => false,
            'zweite_dulle_sticht' => false,
        ]);
        $this->addSql("ALTER TABLE tische ADD regel_einstellungen JSON NOT NULL DEFAULT '{$defaultRegelwerk}'");
        $this->addSql('ALTER TABLE tische ALTER COLUMN regel_einstellungen DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE system_einstellungen');
        $this->addSql('COMMENT ON COLUMN spiele.aktueller_zug_begann_am IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE tisch_spieler DROP moechte_nach_spiel_verlassen');
        $this->addSql('ALTER TABLE tisch_spieler DROP disconnect_seit_am');
        $this->addSql('ALTER TABLE tische DROP auto_start');
        $this->addSql('ALTER TABLE tische DROP naechster_spielstart_am');
        $this->addSql('ALTER TABLE tische DROP menschenlose_seit_am');
        $this->addSql('ALTER TABLE tische DROP regel_einstellungen');
    }
}
